apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-epa-data
  labels:
    app: {{ .Release.Name }}-backend
    component: epa-backend
data:
  real_epa_violations_20250731_144819.json: |
    {{- .Files.Get "../../../real_epa_violations_20250731_144819.json" | nindent 4 }}
