apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-epa-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "backend.name" . }}
    component: epa-backend
data:
  real_epa_violations_20250731_144819.json: |-
    {{ (.Files.Get "files/real_epa_violations_20250731_144819.json") | nindent 4 }}
