apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}-backend
    component: epa-backend
type: Opaque
data:
  anthropic-api-key: {{ .Values.secrets.anthropicApiKey | b64enc }}
  serp-api-key: {{ .Values.secrets.serpApiKey | b64enc }}