apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    app: {{ include "backend.name" . }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws_iam_role_arn }}